### ISSUE TITLE
[Content] Add more information in meta, detail blog, and detail projects

### ISSUE THREAD

**Issue by abdmmar** [abdmmar/website#18]
## Meta
Add meta tag for keywords and article

- [x] keywords -> use tags
- [x] article:published_time
- [x] article:modified_time
- [x] og:image:alt
- [x] ~~extract SEO from Head component~~

## Detail Blog/Projects
Add or change detail information:

- [x] status: draft, in-progress, finished
- [x] published_date
- [x] last_updated_date
- [x] `tags` as `keywords`
- [x] description
- [x] subtitle
- [x] redesign layout for detail information
